// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLJlyJ8Xmg5d54_hKOD16KHhpfwkPUgpQ',
    appId: '1:26008857066:web:836d49f817b3774b49ea93',
    messagingSenderId: '26008857066',
    projectId: 'my-first-pro-1487a',
    authDomain: 'my-first-pro-1487a.firebaseapp.com',
    storageBucket: 'my-first-pro-1487a.firebasestorage.app',
    measurementId: 'G-VG3Z17M041',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD3KnETzTYZQYK17P0abhj8wZ92JZFDV4',
    appId: '1:26008857066:android:6073cb245d0e237e49ea93',
    messagingSenderId: '26008857066',
    projectId: 'my-first-pro-1487a',
    storageBucket: 'my-first-pro-1487a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDdVmYH4aL6FMvky_1y6ELju_IyvtfDh4',
    appId: '1:26008857066:ios:c334ccdb88fcc93e49ea93',
    messagingSenderId: '26008857066',
    projectId: 'my-first-pro-1487a',
    storageBucket: 'my-first-pro-1487a.firebasestorage.app',
    iosBundleId: 'com.example.untitled17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDdVmYH4aL6FMvky_1y6ELju_IyvtfDh4',
    appId: '1:26008857066:ios:c334ccdb88fcc93e49ea93',
    messagingSenderId: '26008857066',
    projectId: 'my-first-pro-1487a',
    storageBucket: 'my-first-pro-1487a.firebasestorage.app',
    iosBundleId: 'com.example.untitled17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLJlyJ8Xmg5d54_hKOD16KHhpfwkPUgpQ',
    appId: '1:26008857066:web:7d968be668a9294149ea93',
    messagingSenderId: '26008857066',
    projectId: 'my-first-pro-1487a',
    authDomain: 'my-first-pro-1487a.firebaseapp.com',
    storageBucket: 'my-first-pro-1487a.firebasestorage.app',
    measurementId: 'G-3W6XDDDEHK',
  );
}
